name: CI - PRIME App Tests, Build y Deploy

on:
  push:
    branches:
      - feature/historial    #se ejecuta solo en tu rama actual
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: 🧩 Checkout del repositorio
        uses: actions/checkout@v4

      - name: ⚙️ Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: 📦 Instalar dependencias
        run: npm ci
      
      - name: 📦 Instalar EAS CLI
        run: npm install -g eas-cli

      - name: 🔐 Autenticar en Expo
        run: npx eas whoami
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
      
      - name: 🧪 Ejecutar pruebas unitarias
        run: npm run test:unit

      - name: 🧾 Mostrar resultado
        run: echo "✅ Pruebas ejecutadas correctamente en CI"
      
      - name: 🚀 Construir y desplegar la app en EAS
        run: |
          npx eas build --platform android --profile preview
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
